# Generated by Django 4.0.10 on 2023-06-03 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OhHai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Oh Hai', max_length=200)),
            ],
        ),
    ]
