# Generated by Django 4.0.10 on 2023-06-03 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsa', '0002_ohhai'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OhHai',
        ),
    ]
