# Generated by Django 4.0.10 on 2023-10-21 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsa', '0003_delete_ohhai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='supplier',
        ),
        migrations.AddField(
            model_name='vendor',
            name='suppliers',
            field=models.ManyToManyField(related_name='vendors', to='cmsa.supplier'),
        ),
    ]
