# Generated by Django 4.0.10 on 2023-10-28 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsa', '0005_vendor_contact_email_vendor_contact_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='website',
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
