# Generated by Django 4.0.10 on 2023-11-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsa', '0007_supplier_account_active_supplier_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='website_password',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
