# Generated by Django 4.0.10 on 2023-11-12 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsa', '0008_alter_supplier_website_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('role', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='supplier',
            name='contacts',
            field=models.ManyToManyField(blank=True, to='cmsa.contact'),
        ),
    ]
