# Generated by Django 4.0.10 on 2023-11-12 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsa', '0009_contact_supplier_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='primary_contact',
            field=models.BooleanField(default=False),
        ),
    ]
