# Generated by Django 4.0.10 on 2023-11-26 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsa', '0010_contact_primary_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
