# Generated by Django 4.0.10 on 2023-11-26 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsa', '0011_contact_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
    ]
